name: PyPI macos arm64 deployer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.15]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Make extension build mandatory
      run: touch .cibuildwheel
    - name: Install Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.1
      env:
        CIBW_BEFORE_BUILD: "pip install wheel cython"
        CIBW_ARCHS_MACOS: "universal2 arm64"
        CIBW_BUILD: cp38-*
    - name: Save wheels
      uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    needs: wheels
    runs-on: ubuntu-latest
    steps:
      - run: ls -l ./wheelhouse/*
