name: Python 3.10 for manylinux PyPI deployer
on:
  workflow_dispatch:

jobs:
  # Special case: additional upload by twine breaks, because some releases
  # already exist!
  # Build and deploy only Python 3.10 wheel for manylinux
  Linux-build:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and upload manylinux wheels
        uses:  mozman/manylinux-wheel-builder@master
        with:
          python-versions: "3.10"
