name: manually test binary wheel builder
on:
  workflow_dispatch
jobs:
  # Test build wheels for macOS, Linux and Windows
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build binary wheels
        run: |
          pip install wheel cython
          python setup.py bdist_wheel
        continue-on-error: true
